### ISSUE TITLE
Multi Image Problem

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbrypress#1]
Currently, lbrypress publishes several copies of each image to support multiple sizes and resolutions.

The approach to eliminate this is not solidified, but most likely involves solving https://github.com/lbryio/spee.ch/issues/749 and using that functionality to resize images.

**Comment by prkirby** [comment]
Fixed on our end, using the protocol shown in  lbryio/spee.ch#749. Only uploading main image to spee.ch
