### ISSUE TITLE
Analytics for LBRY

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbrypress#6]
How can LBRY, Inc. know about how many plugin installs have happened and how many are actively being used?

It's possible WordPress provides this to plugin developers, but if not, it'd be good to add some basic reports/calls for this.

**Comment by jsigwart** [comment]
Complete the plugin and package it up and upload it to https://wordpress.org/plugins/

There is a complete system there that tracks the number of installs, and there is a rating system there, too. It also allows the plugin to be discovered inside of WordPress in the plugin search. Info here: https://wordpress.org/plugins/developers/

**Comment by prkirby** [comment]
Yes this will all be included in being part of the public plugin 'store'. We will have to move it to their SVN repo and have it reviewed before going public. We will have to create a LBRY wordpress.org account, or optionally that can be done through my business name.
